#ifndef DEFGLOB_LIBSAM
#define DEFGLOB_LIBSAM

#define PI 3.14159265359
#define M_PI 3.141592
#define ITERMAX 50
#define PODBORMAX 2000
#define ERRDPABS_E 1.0e-12 // 1.0e-8
#define ERRDPABS_W 1.0e-1 // 1.0e3
#define ERRDPREL_W 1.0e-2
#define SCALE_X_W  2e7
#define SCALE_Y_W 2.5e7
#define SCALE_X_hE 5e-5
#define SCALE_Y_hE 5e-5
#define SUBITERMAX 2
typedef double Real;
typedef unsigned Index;
// ---------------- new ---------------
#define EXP_POW_MAX  709.7
#define EXP_POW_MIN  -708.6
#define BIGINT 10000
// ------------------------------------
#endif